### ISSUE TITLE
Crash on sharing logs

### ISSUE THREAD

**Issue by devesh-shetty** [Gridstone/DebugDrawer#72]
```
  java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/{package-namje}/files/2023-06-26T23:01:52+0400.log
                                                                                                    	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
                                                                                                    	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
                                                                                                    	at au.com.gridstone.debugdrawer.timber.LogsDialog$share$1.invoke(LogsDialog.kt:77)
                                                                                                    	at au.com.gridstone.debugdrawer.timber.LogsDialog$share$1.invoke(LogsDialog.kt:73)
                                                                                                    	at au.com.gridstone.debugdrawer.timber.LumberYard$SaveTask.onPostExecute(LumberYard.kt:111)
```

**Comment by devesh-shetty** [comment]
ah, just had to update my file provider paths
